---
title: berntzone
author: Arvid Berntsson
email: arvid@bernt.zone
description: Arvid is a UX/UI designer and a student in Industrial Design Engineering.
  Currently doing his masters at Lund University. Don't be shy, say hello!
baseurl: "/berntzone.github.io"
url: ''
defaults:
- scope: ''
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
