---
title: berntzone
author: Arvid Berntsson
email: arvid@bernt.zone
description: Arvid is an Industrial Design Engineering student doing his masters.
  Say hello!
baseurl: "/berntzone.github.io"
url: ''
defaults:
- scope: ''
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
